trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'AppServiceConnection'
  webAppName: 'm-zhehistovskyi-web-app'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '10.0.x'

  - script: dotnet restore
    displayName: 'Restore'

  - script: dotnet build --configuration $(buildConfiguration) --no-restore
    displayName: 'Build'

  - script: dotnet publish ConferenceRoomBooking.Web.csproj --configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)/publish
    displayName: 'Publish'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/ConferenceRoomBooking.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/ConferenceRoomBooking.zip'
      ArtifactName: 'drop'

  - task: AzureWebApp@1
    displayName: 'Deploy'
    inputs:
      azureSubscription: '$(azureSubscription)'
      appType: 'webApp'
      appName: '$(webAppName)'
      package: '$(Build.ArtifactStagingDirectory)/ConferenceRoomBooking.zip'
      deploymentMethod: 'auto'