services:
  conferenceroombooking.web:
    image: conferenceroombooking.web
    container_name: conferenceroombooking.web
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5000:8080"
    build:
      context: .
      dockerfile: ConferenceRoomBooking.Web/Dockerfile
