services:
  conferenceroombooking.web:
    image: conferenceroombooking.web
    container_name: conferenceroombooking.web
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=ConferenceRoomBookingDb;User Id=sa;Password=Dii1kKta9Tv8;TrustServerCertificate=True;"
    ports:
      - "5000:8080"
    build:
      context: .
      dockerfile: ConferenceRoomBooking.Web/Dockerfile
    depends_on:
      sqlserver:
        condition: service_healthy

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: conferenceroombooking.sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Dii1kKta9Tv8"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$SA_PASSWORD\" -C -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

volumes:
  sqlserver-data:
