FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["ConferenceRoomBooking.Web/ConferenceRoomBooking.Web.csproj", "ConferenceRoomBooking.Web/"]
COPY ["ConferenceRoomBooking.Bll/ConferenceRoomBooking.Bll.csproj", "ConferenceRoomBooking.Bll/"]
COPY ["ConferenceRoomBooking.Bll.Common/ConferenceRoomBooking.Bll.Common.csproj", "ConferenceRoomBooking.Bll.Common/"]
COPY ["ConferenceRoomBooking.Dal.SqlRepositories/ConferenceRoomBooking.Dal.SqlRepositories.csproj", "ConferenceRoomBooking.Dal.SqlRepositories/"]
RUN dotnet restore "ConferenceRoomBooking.Web/ConferenceRoomBooking.Web.csproj"
COPY . .
WORKDIR "/src/ConferenceRoomBooking.Web"
RUN dotnet build "./ConferenceRoomBooking.Web.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./ConferenceRoomBooking.Web.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ConferenceRoomBooking.Web.dll"]
