// <auto-generated />
using System;
using ConferenceRoomBooking.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConferenceRoomBooking.DataLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConferenceRoomBooking.DataLayer.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseHourRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("ConferenceRoomBooking.DataLayer.Entities.RoomServiceOption", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceOptionId")
                        .HasColumnType("int");

                    b.HasKey("RoomId", "ServiceOptionId");

                    b.HasIndex("ServiceOptionId");

                    b.ToTable("RoomServiceOptions");
                });

            modelBuilder.Entity("ConferenceRoomBooking.DataLayer.Entities.ServiceOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ServiceOptions");
                });

            modelBuilder.Entity("ConferenceRoomBooking.DataLayer.Entities.RoomServiceOption", b =>
                {
                    b.HasOne("ConferenceRoomBooking.DataLayer.Entities.Room", "Room")
                        .WithMany("RoomServiceOptions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenceRoomBooking.DataLayer.Entities.ServiceOption", "ServiceOption")
                        .WithMany("RoomServiceOptions")
                        .HasForeignKey("ServiceOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("ServiceOption");
                });

            modelBuilder.Entity("ConferenceRoomBooking.DataLayer.Entities.Room", b =>
                {
                    b.Navigation("RoomServiceOptions");
                });

            modelBuilder.Entity("ConferenceRoomBooking.DataLayer.Entities.ServiceOption", b =>
                {
                    b.Navigation("RoomServiceOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
